#![forbid(unsafe_code)]
#![allow(clippy::too_many_lines, clippy::cast_precision_loss)]

use std::collections::{BTreeMap, BTreeSet, VecDeque};
use std::fs::{self, OpenOptions};
use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use regex::Regex;
use rusqlite::{params, Connection, OptionalExtension};
use serde_json::{json, Map, Value};
use syntavra_core::sha256_hex;

const ACTIONS: &[&str] = &[
    "rewrite","transcript-mine","watch","dashboard","worker","cache-plan","cache-health",
    "notify","provider-route","provider-pool","delegate","code-intel",
];

pub(crate) fn supports(command:&[String])->bool{
    command.len()==2&&command[0]=="run"&&ACTIONS.contains(&command[1].as_str())
}

pub(crate) fn execute(command:&[String],arguments:&[String],project:&Path,state_root:&Path)->Result<Option<Value>,String>{
    if !supports(command){return Ok(None)}
    match command[1].as_str(){
        "rewrite"=>rewrite_action(arguments).map(Some),
        "transcript-mine"=>transcript_mine(arguments).map(Some),
        "watch"=>watch_action(arguments,project,state_root).map(Some),
        "dashboard"=>dashboard_action(arguments,project,state_root).map(Some),
        "worker"=>worker_action(arguments,project,state_root).map(Some),
        "cache-plan"=>cache_plan(arguments,state_root).map(Some),
        "cache-health"=>cache_health(state_root).map(Some),
        "notify"=>notify_action(arguments,state_root).map(Some),
        "provider-route"=>provider_route_action(arguments).map(Some),
        "provider-pool"=>provider_pool_action(arguments,state_root).map(Some),
        "delegate"=>delegate_action(arguments).map(Some),
        "code-intel"=>code_intel(arguments,project,state_root).map(Some),
        _=>Ok(None),
    }
}

#[derive(Clone,Copy)]
struct RewriteRule{exe:&'static str,prefix:&'static str,append:&'static[&'static str],blocked:&'static[&'static str],name:&'static str}
const RULES:&[RewriteRule]=&[
    RewriteRule{exe:"git",prefix:"status",append:&["--porcelain=v2","--branch"],blocked:&["--short","--porcelain","-s"],name:"git-status"},
    RewriteRule{exe:"git",prefix:"log",append:&["--oneline","--decorate=no","-n","40"],blocked:&["--format","--pretty","--oneline","-p","--patch"],name:"git-log"},
    RewriteRule{exe:"git",prefix:"diff",append:&["--stat","--compact-summary"],blocked:&["--stat","--name-only","--name-status","--numstat","-p","--patch"],name:"git-diff-stat"},
    RewriteRule{exe:"git",prefix:"show",append:&["--stat","--oneline"],blocked:&["--stat","--format","--pretty","-p","--patch"],name:"git-show-stat"},
    RewriteRule{exe:"rg",prefix:"",append:&["--no-heading","--line-number","--color=never"],blocked:&["--heading","--json","--vimgrep","--color"],name:"rg"},
    RewriteRule{exe:"grep",prefix:"",append:&["-n","--color=never"],blocked:&["-n","--line-number","--color"],name:"grep"},
    RewriteRule{exe:"ls",prefix:"",append:&["-1","--color=never"],blocked:&["-l","--long","-1","--color"],name:"ls"},
    RewriteRule{exe:"pytest",prefix:"",append:&["-q","--tb=short"],blocked:&["-q","--quiet","-v","--verbose","--tb"],name:"pytest"},
    RewriteRule{exe:"py.test",prefix:"",append:&["-q","--tb=short"],blocked:&["-q","--quiet","-v","--verbose","--tb"],name:"py-test"},
    RewriteRule{exe:"cargo",prefix:"test",append:&["--quiet"],blocked:&["--quiet","-q","--verbose","-v"],name:"cargo-test"},
    RewriteRule{exe:"cargo",prefix:"check",append:&["--quiet"],blocked:&["--quiet","-q","--verbose","-v"],name:"cargo-check"},
    RewriteRule{exe:"go",prefix:"test",append:&["-json"],blocked:&["-json","-v"],name:"go-test"},
    RewriteRule{exe:"npm",prefix:"test",append:&["--silent"],blocked:&["--silent","--loglevel"],name:"npm-test"},
    RewriteRule{exe:"pnpm",prefix:"test",append:&["--silent"],blocked:&["--silent","--reporter"],name:"pnpm-test"},
    RewriteRule{exe:"yarn",prefix:"test",append:&["--silent"],blocked:&["--silent","--verbose"],name:"yarn-test"},
    RewriteRule{exe:"jest",prefix:"",append:&["--silent","--reporters=default"],blocked:&["--silent","--verbose","--json","--reporters"],name:"jest"},
    RewriteRule{exe:"vitest",prefix:"",append:&["--reporter=basic"],blocked:&["--reporter","--silent"],name:"vitest"},
    RewriteRule{exe:"ruff",prefix:"check",append:&["--output-format=concise"],blocked:&["--output-format","--verbose"],name:"ruff"},
    RewriteRule{exe:"mypy",prefix:"",append:&["--no-error-summary","--show-column-numbers"],blocked:&["--pretty","--no-error-summary"],name:"mypy"},
    RewriteRule{exe:"eslint",prefix:"",append:&["--format=compact"],blocked:&["--format","-f"],name:"eslint"},
    RewriteRule{exe:"docker",prefix:"logs",append:&["--tail=200"],blocked:&["--tail","-n","--follow","-f"],name:"docker-logs"},
    RewriteRule{exe:"kubectl",prefix:"logs",append:&["--tail=200"],blocked:&["--tail","-f","--follow"],name:"kubectl-logs"},
    RewriteRule{exe:"aws",prefix:"",append:&["--output","json","--no-cli-pager"],blocked:&["--output","--cli-auto-prompt"],name:"aws"},
    RewriteRule{exe:"gcloud",prefix:"",append:&["--format=json","--quiet"],blocked:&["--format","--verbosity"],name:"gcloud"},
    RewriteRule{exe:"az",prefix:"",append:&["--output","json"],blocked:&["--output","-o"],name:"az"},
    RewriteRule{exe:"systemctl",prefix:"status",append:&["--no-pager","--plain"],blocked:&["--no-pager","--output"],name:"systemctl"},
    RewriteRule{exe:"journalctl",prefix:"",append:&["--no-pager","-n","200","-o","short-iso"],blocked:&["--no-pager","-n","--lines","-o","--output","-f"],name:"journalctl"},
    RewriteRule{exe:"dotnet",prefix:"test",append:&["--verbosity","minimal"],blocked:&["--verbosity","-v"],name:"dotnet-test"},
    RewriteRule{exe:"mvn",prefix:"",append:&["-q"],blocked:&["-q","-X","--debug"],name:"maven-test"},
    RewriteRule{exe:"ctest",prefix:"",append:&["--output-on-failure","--no-tests=error"],blocked:&["--verbose","-V"],name:"ctest"},
];

fn rewrite_action(arguments:&[String])->Result<Value,String>{
    let start=arguments.windows(2).position(|row|row[0]=="run"&&row[1]=="rewrite").map(|index|index+2).ok_or_else(||"REWRITE_ACTION_NOT_FOUND".to_owned())?;
    let argv=arguments[start..].iter().filter(|value|value.as_str()!="--").cloned().collect::<Vec<_>>();
    if argv.is_empty(){return Err("rewrite command is required".to_owned())}
    rewrite_argv(&argv)
}
fn rewrite_argv(argv:&[String])->Result<Value,String>{
    let original=argv.to_vec();let unsafe_re=Regex::new(r"(?:\|\||&&|[|;`]|\$\(|\n|\r|>|<)").map_err(|error|format!("REWRITE_REGEX_FAILED:{error}"))?;
    if argv.iter().any(|part|unsafe_re.is_match(part)){return Ok(json!({"original":original,"rewritten":original,"changed":false,"rule":Value::Null,"safe":false,"reason":"unsafe shell syntax detected"}))}
    let mut offset=0usize;if argv.first().is_some_and(|value|value=="env"){offset=1;while offset<argv.len()&&argv[offset].contains('=')&&!argv[offset].starts_with('-'){offset+=1;}}
    if argv.first().is_some_and(|value|matches!(value.as_str(),"sudo"|"su"|"doas")){return Ok(json!({"original":original,"rewritten":original,"changed":false,"rule":Value::Null,"safe":false,"reason":"privilege wrapper is not rewritten"}))}
    let Some(exe)=argv.get(offset)else{return Ok(json!({"original":original,"rewritten":original,"changed":false,"rule":Value::Null,"safe":true,"reason":"no matching safe rewrite rule"}))};
    let tail=&argv[offset+1..];let joined=tail.join(" ");
    for rule in RULES{if exe!=rule.exe{continue}if !rule.prefix.is_empty()&&!joined.starts_with(rule.prefix){continue}if rule.blocked.iter().any(|flag|tail.iter().any(|part|part==flag||part.starts_with(&format!("{flag}=")))){return Ok(json!({"original":original,"rewritten":original,"changed":false,"rule":Value::Null,"safe":true,"reason":"explicit human-oriented or conflicting output option present"}))}let mut rewritten=argv.to_vec();for flag in rule.append{rewritten.push((*flag).to_owned());}return Ok(json!({"original":original,"rewritten":rewritten,"changed":rewritten!=argv,"rule":rule.name,"safe":true,"reason":"reduce machine-irrelevant output"}))}
    Ok(json!({"original":original,"rewritten":original,"changed":false,"rule":Value::Null,"safe":true,"reason":"no matching safe rewrite rule"}))
}

fn transcript_mine(arguments:&[String])->Result<Value,String>{
    let source=positional_after(arguments,"transcript-mine",0,&[])?;let text=if Path::new(source).is_file(){fs::read_to_string(source).map_err(|error|format!("TRANSCRIPT_READ_FAILED:{error}"))?}else{source.to_owned()};let events=load_transcript(&text);let mut opportunities=Vec::<Value>::new();let mut commands=0usize;for(index,row)in events.iter().enumerate(){let command=transcript_field(row,&["command","cmd","shell_command","input"]);if command.is_empty(){continue}commands+=1;let output=transcript_field(row,&["output","stdout","result","content"]);let input_tokens=((command.as_bytes().len()+output.as_bytes().len())/4).max(1);let argv=shellish_split(&command);let rewrite=rewrite_argv(&argv)?;if rewrite["changed"].as_bool().unwrap_or(false){opportunities.push(json!({"index":index,"command":command,"kind":"pre-tool-rewrite","estimated_input_tokens":input_tokens,"estimated_saved_tokens":(output.len()/20).max(8),"recommendation":"rewrite before execution","rule":rewrite["rule"],"compactor":Value::Null}))}let lines=output.lines().count();if lines>30{let keep=output.lines().rev().take(20).collect::<Vec<_>>().into_iter().rev().collect::<Vec<_>>().join("\n");let saved=(output.as_bytes().len().saturating_sub(keep.as_bytes().len()))/4;if saved>0{opportunities.push(json!({"index":index,"command":command,"kind":"post-tool-compaction","estimated_input_tokens":input_tokens,"estimated_saved_tokens":saved,"recommendation":"capture exact output and return compact view","rule":Value::Null,"compactor":compactor_name(&command)}));}}}let total=opportunities.iter().map(|row|row["estimated_saved_tokens"].as_u64().unwrap_or(0)).sum::<u64>();let mut body=json!({"events":events.len(),"commands":commands,"opportunities":opportunities,"estimated_saved_tokens":total,"coverage":{"rewrite_rules":112,"compactors":112}});body["analysis_hash"]=Value::String(sha256_hex(canonical_json(&body)?.as_bytes()));Ok(body)
}
fn load_transcript(text:&str)->Vec<Value>{if let Ok(value)=serde_json::from_str::<Value>(text){if let Some(rows)=value.as_array(){return rows.iter().filter(|row|row.is_object()).cloned().collect()}if let Some(rows)=value.get("events").or_else(||value.get("messages")).or_else(||value.get("transcript")).and_then(Value::as_array){return rows.iter().filter(|row|row.is_object()).cloned().collect()}}text.lines().filter_map(|line|serde_json::from_str::<Value>(line).ok()).filter(Value::is_object).collect()}
fn transcript_field(row:&Value,keys:&[&str])->String{for key in keys{if let Some(value)=row[*key].as_str(){return value.to_owned()}}if let Some(input)=row.get("tool_input").or_else(||row.get("arguments")).and_then(Value::as_object){for key in ["command","cmd"]{if let Some(value)=input.get(key).and_then(Value::as_str){return value.to_owned()}}}String::new()}
fn shellish_split(value:&str)->Vec<String>{value.split_whitespace().map(str::to_owned).collect()}
fn compactor_name(command:&str)->&'static str{let lower=command.to_lowercase();if lower.contains("pytest")||lower.contains("test"){"test-summary"}else if lower.starts_with("git status"){"git-status"}else{"generic-tail"}}

fn cache_plan(arguments:&[String],state_root:&Path)->Result<Value,String>{let source=positional_after(arguments,"cache-plan",0,&["--provider","--model","--ttl"])?;let messages=load_json(source)?;let rows=messages.as_array().ok_or_else(||"cache-plan source must contain a JSON message list".to_owned())?;let provider=required_option(arguments,"--provider")?.trim().to_lowercase();let model=required_option(arguments,"--model")?;let ttl=option_value(arguments,"--ttl")?.map(|value|value.parse::<i64>().map_err(|_|"CACHE_TTL_INVALID".to_owned())).transpose()?.unwrap_or_else(||provider_ttl(&provider));let reorder=!has_flag(arguments,"--no-reorder");let now=now_seconds()?;let stable=rows.iter().filter(|row|stable_message(row)).cloned().collect::<Vec<_>>();let volatile=rows.iter().filter(|row|!stable_message(row)).cloned().collect::<Vec<_>>();let ordered=if reorder{stable.iter().chain(volatile.iter()).cloned().collect::<Vec<_>>()}else{rows.clone()};let stable_prefix=ordered.iter().take(stable.len()).map(clean_cache_value).collect::<Vec<_>>();let stable_hash=sha256_hex(canonical_json(&Value::Array(stable_prefix))?.as_bytes());let mut segments=Vec::<Value>::new();let(mut cacheable,mut volatile_tokens)=(0i64,0i64);for row in &ordered{let clean=clean_cache_value(row);let raw=canonical_json(&clean)?;let is_stable=stable_message(row);let tokens=(raw.as_bytes().len()/4).max(1) as i64;if is_stable{cacheable+=tokens}else{volatile_tokens+=tokens}segments.push(json!({"role":row["role"].as_str().unwrap_or("unknown"),"stable":is_stable,"bytes":raw.as_bytes().len(),"tokens_estimate":tokens,"content_hash":sha256_hex(raw.as_bytes()),"reason":if is_stable{"stable-prefix"}else{"volatile-tail"}}));}let plan=json!({"provider":provider,"model":model,"stable_prefix_hash":stable_hash,"stable_messages":stable.len(),"volatile_messages":volatile.len(),"cacheable_tokens":cacheable,"volatile_tokens":volatile_tokens,"ttl_seconds":ttl,"expires_at":now+ttl as f64,"refresh_after":now+(ttl as f64*0.75),"reordered":reorder&&ordered!=*rows,"segments":segments});save_cache_plan(state_root,&plan)?;Ok(plan)}
fn stable_message(row:&Value)->bool{let role=row["role"].as_str().unwrap_or_default().to_lowercase();matches!(role.as_str(),"system"|"developer")||(role=="tool"&&row["cache_control"].as_str()==Some("stable"))||row["stable"].as_bool().unwrap_or(false)||row["cacheable"].as_bool().unwrap_or(false)}
fn clean_cache_value(value:&Value)->Value{match value{Value::Object(map)=>{let volatile=["timestamp","request_id","trace_id","nonce","usage","cost","latency_ms"];let mut keys=map.keys().collect::<Vec<_>>();keys.sort_unstable();let mut out=Map::new();for key in keys{if volatile.contains(&key.as_str())||key.starts_with('_'){continue}out.insert(key.clone(),clean_cache_value(&map[key]));}Value::Object(out)},Value::Array(rows)=>Value::Array(rows.iter().map(clean_cache_value).collect()),_=>value.clone()}}
fn provider_ttl(provider:&str)->i64{match provider{"anthropic"=>300,"google"|"gemini"=>3600,_=>600}}
fn cache_path(state_root:&Path)->PathBuf{state_root.join("cache/plans.json")}
fn save_cache_plan(state_root:&Path,plan:&Value)->Result<(),String>{let path=cache_path(state_root);if let Some(parent)=path.parent(){fs::create_dir_all(parent).map_err(|error|format!("CACHE_PARENT_FAILED:{error}"))?;}let mut current=if path.is_file(){serde_json::from_slice::<Value>(&fs::read(&path).map_err(|error|format!("CACHE_READ_FAILED:{error}"))?).unwrap_or_else(|_|json!({}))}else{json!({})};if !current.is_object(){current=json!({})}if !current["plans"].is_object(){current["plans"]=json!({})}let key=format!("{}:{}:{}",plan["provider"].as_str().unwrap_or_default(),plan["model"].as_str().unwrap_or_default(),plan["stable_prefix_hash"].as_str().unwrap_or_default());current["plans"][key]=plan.clone();current["updated_at"]=Value::from(now_seconds()?);atomic_write_json(&path,&current)}
fn cache_health(state_root:&Path)->Result<Value,String>{let path=cache_path(state_root);let current=if path.is_file(){serde_json::from_slice::<Value>(&fs::read(path).map_err(|error|format!("CACHE_READ_FAILED:{error}"))?).unwrap_or_else(|_|json!({}))}else{json!({})};let now=now_seconds()?;let rows=current["plans"].as_object().map(|map|map.values().collect::<Vec<_>>()).unwrap_or_default();let active=rows.iter().filter(|row|now<row["refresh_after"].as_f64().unwrap_or(0.0)).count();let refresh=rows.iter().filter(|row|{let r=row["refresh_after"].as_f64().unwrap_or(0.0);let e=row["expires_at"].as_f64().unwrap_or(0.0);r<=now&&now<e}).count();let expired=rows.iter().filter(|row|row["expires_at"].as_f64().unwrap_or(0.0)<=now).count();let tokens=rows.iter().map(|row|row["cacheable_tokens"].as_i64().unwrap_or(0)).sum::<i64>();Ok(json!({"plans":rows.len(),"active":active,"refresh_due":refresh,"expired":expired,"cacheable_tokens":tokens}))}

fn notify_action(arguments:&[String],state_root:&Path)->Result<Value,String>{let title=positional_after(arguments,"notify",0,&["--severity","--channel","--discord-webhook","--telegram-token","--telegram-chat"])?;let body=positional_after(arguments,"notify",1,&["--severity","--channel","--discord-webhook","--telegram-token","--telegram-chat"])?;let severity=option_value(arguments,"--severity")?.unwrap_or_else(||"info".to_owned());if !matches!(severity.as_str(),"info"|"warning"|"critical"){return Err("NOTIFICATION_SEVERITY_INVALID".to_owned())}let channel=option_value(arguments,"--channel")?.unwrap_or_else(||"local".to_owned());let created=now_seconds()?;let base=json!({"channel":channel,"severity":severity,"title":title,"body":body,"created_at":created});let mut item=base.clone();item["event_hash"]=Value::String(sha256_hex(canonical_json(&base)?.as_bytes()));let path=state_root.join("notifications/events.jsonl");if let Some(parent)=path.parent(){fs::create_dir_all(parent).map_err(|error|format!("NOTIFICATION_PARENT_FAILED:{error}"))?;}let mut file=OpenOptions::new().create(true).append(true).open(&path).map_err(|error|format!("NOTIFICATION_OPEN_FAILED:{error}"))?;writeln!(file,"{}",canonical_json(&item)?).map_err(|error|format!("NOTIFICATION_WRITE_FAILED:{error}"))?;let mut delivery=Map::new();if let Some(url)=option_value(arguments,"--discord-webhook")?.filter(|value|!value.is_empty()){delivery.insert("discord".to_owned(),post_json_curl(&url,&json!({"content":format!("[{}] {}\n{}",severity.to_uppercase(),title,body)})));}if let(Some(token),Some(chat))=(option_value(arguments,"--telegram-token")?.filter(|v|!v.is_empty()),option_value(arguments,"--telegram-chat")?.filter(|v|!v.is_empty())){let url=format!("https://api.telegram.org/bot{token}/sendMessage");delivery.insert("telegram".to_owned(),post_json_curl(&url,&json!({"chat_id":chat,"text":format!("[{}] {}\n{}",severity.to_uppercase(),title,body)})));}Ok(json!({"notification":item,"delivery":delivery}))}
fn post_json_curl(url:&str,payload:&Value)->Value{if !command_exists("curl"){return json!({"ok":false,"error":"curl-unavailable"})}let output=Command::new("curl").args(["--silent","--show-error","--output","/dev/null","--write-out","%{http_code}","--max-time","10","-H","Content-Type: application/json","-X","POST","--data",&payload.to_string(),url]).stdin(Stdio::null()).output();match output{Ok(value)=>{let status=String::from_utf8_lossy(&value.stdout).trim().parse::<u16>().unwrap_or(0);json!({"ok":value.status.success()&&(200..300).contains(&status),"status":status})},Err(error)=>json!({"ok":false,"error":format!("{}",error.kind())})}}

fn provider_route_action(arguments:&[String])->Result<Value,String>{let task=positional_after(arguments,"provider-route",0,&["--changed-files","--tokens"])?;let source=positional_after(arguments,"provider-route",1,&["--changed-files","--tokens"])?;let rows=load_json(source)?;let candidates=rows.as_array().ok_or_else(||"provider candidates must be a JSON list".to_owned())?;route_candidates(task,candidates,option_i64(arguments,"--changed-files",0)?,option_i64(arguments,"--tokens",0)?,now_seconds()?,true)}
fn complexity(task:&str,changed:i64,tokens:i64)->&'static str{let corpus=task.to_lowercase();let mut score=0;score+=if ["architecture","security","migration","race condition","formal","proof","root cause"].iter().any(|term|corpus.contains(term)){2}else{0};score+=if ["refactor","debug","benchmark","cross-repo","dependency"].iter().any(|term|corpus.contains(term)){1}else{0};score+=i32::from(changed>=8);score+=i32::from(tokens>=16000);if score>=4{"reasoning"}else if score>=2{"complex"}else if score==1{"medium"}else{"simple"}}
fn complexity_rank(value:&str)->i32{match value{"simple"=>0,"medium"=>1,"complex"=>2,"reasoning"=>3,_=>0}}
fn route_candidates(task:&str,rows:&[Value],changed:i64,tokens:i64,now:f64,prefer_subscription:bool)->Result<Value,String>{let needed=complexity(task,changed,tokens);let mut ranked=Vec::<(f64,String,String,String,Vec<String>)>::new();for row in rows{if !row["available"].as_bool().unwrap_or(true)||row["rate_limited_until"].as_f64().unwrap_or(0.0)>now||row["quota_remaining"].as_f64().unwrap_or(1.0)<=0.0||complexity_rank(row["max_complexity"].as_str().unwrap_or("reasoning"))<complexity_rank(needed)||(row["context_window"].as_i64().unwrap_or(0)>0&&tokens>row["context_window"].as_i64().unwrap_or(0)){continue}let provider=row["provider"].as_str().unwrap_or_default().to_owned();let model=row["model"].as_str().unwrap_or_default().to_owned();let account=row["account"].as_str().unwrap_or("default").to_owned();let quality=row["quality"].as_f64().unwrap_or(0.5);let quota=row["quota_remaining"].as_f64().unwrap_or(1.0);let input=row["input_cost_per_million"].as_f64().unwrap_or(0.0);let output=row["output_cost_per_million"].as_f64().unwrap_or(0.0);let latency=row["latency_ms"].as_f64().unwrap_or(0.0);let priority=row["priority"].as_i64().unwrap_or(0).clamp(-20,20);let blended=input+output*2.0;let mut score=quality*60.0-blended*2.0-latency/1000.0+quota.mul_add(20.0,0.0).min(20.0)+priority as f64*0.5;let mut reasons=Vec::new();if prefer_subscription&&row["subscription"].as_bool().unwrap_or(false){score+=15.0;reasons.push("subscription-account".to_owned())}else if blended==0.0{reasons.push("zero-priced-model".to_owned())}reasons.extend([format!("quality={quality:.3}"),format!("quota={quota:.3}"),format!("priority={priority}"),format!("latency_ms={latency:.1}"),format!("cost_index={blended:.4}")]);ranked.push((score,provider,model,account,reasons));}if ranked.is_empty(){return Err("no provider satisfies availability, quota, rate-limit, context and complexity constraints".to_owned())}ranked.sort_by(|a,b|b.0.partial_cmp(&a.0).unwrap_or(std::cmp::Ordering::Equal).then_with(||a.1.cmp(&b.1)).then_with(||a.2.cmp(&b.2)).then_with(||a.3.cmp(&b.3)));let(selected_score,provider,model,account,reasons)=ranked[0].clone();let fallbacks=ranked.iter().skip(1).take(5).map(|(_,p,m,a,_)|json!([p,m,a])).collect::<Vec<_>>();let body=json!({"provider":provider,"model":model,"account":account,"complexity":needed,"score":selected_score,"reasons":reasons,"fallbacks":fallbacks});let hash=sha256_hex(canonical_json(&body)?.as_bytes());let mut result=body;result["receipt_hash"]=Value::String(hash);Ok(result)}

fn provider_pool_path(state_root:&Path)->PathBuf{state_root.join("provider-accounts.sqlite3")}
fn initialize_pool(path:&Path)->Result<Connection,String>{let connection=Connection::open(path).map_err(|error|format!("PROVIDER_POOL_OPEN_FAILED:{error}"))?;connection.execute_batch("PRAGMA journal_mode=WAL;PRAGMA busy_timeout=30000;CREATE TABLE IF NOT EXISTS provider_accounts(provider TEXT NOT NULL,account TEXT NOT NULL,credential_ref TEXT NOT NULL,subscription INTEGER NOT NULL DEFAULT 0,priority INTEGER NOT NULL DEFAULT 0,quota_remaining REAL NOT NULL DEFAULT 1.0,quota_reset_at REAL NOT NULL DEFAULT 0.0,rate_limited_until REAL NOT NULL DEFAULT 0.0,circuit_open_until REAL NOT NULL DEFAULT 0.0,latency_ewma_ms REAL NOT NULL DEFAULT 0.0,success_count INTEGER NOT NULL DEFAULT 0,failure_count INTEGER NOT NULL DEFAULT 0,consecutive_failures INTEGER NOT NULL DEFAULT 0,disabled INTEGER NOT NULL DEFAULT 0,model_allowlist_json TEXT NOT NULL DEFAULT '[]',updated_at REAL NOT NULL,PRIMARY KEY(provider,account));").map_err(|error|format!("PROVIDER_POOL_INIT_FAILED:{error}"))?;Ok(connection)}
fn provider_pool_action(arguments:&[String],state_root:&Path)->Result<Value,String>{let values=positionals_after(arguments,"provider-pool",&["--quota","--quota-reset-at","--model","--latency-ms","--retry-after","--changed-files","--tokens"])?;let action=values.first().copied().unwrap_or_default();let provider=values.get(1).copied().unwrap_or_default();let account=values.get(2).copied().unwrap_or_default();let value=values.get(3).copied().unwrap_or_default();let path=provider_pool_path(state_root);if let Some(parent)=path.parent(){fs::create_dir_all(parent).map_err(|error|format!("PROVIDER_POOL_PARENT_FAILED:{error}"))?;}let connection=initialize_pool(&path)?;match action{"add"=>pool_add(arguments,&connection,provider,account,value),"feedback"=>pool_feedback(arguments,&connection,provider,account),"list"=>pool_receipt(&connection),"route"=>{let models=load_json(value)?;let model_rows=models.as_array().ok_or_else(||"route requires model JSON list/path as value".to_owned())?;let candidates=pool_candidates(&connection,model_rows,now_seconds()?,provider)?;route_candidates("provider-account-route",&candidates,option_i64(arguments,"--changed-files",0)?,option_i64(arguments,"--tokens",0)?,now_seconds()?,true)},_=>Err(format!("PROVIDER_POOL_ACTION_INVALID:{action}"))}}
fn validate_provider_account(provider:&str,account:&str)->Result<(String,String),String>{let provider=provider.trim().to_lowercase();let account=account.trim().to_owned();let provider_re=Regex::new(r"^[a-z0-9][a-z0-9_.-]{0,63}$").map_err(|error|format!("POOL_REGEX_FAILED:{error}"))?;let account_re=Regex::new(r"^[A-Za-z0-9][A-Za-z0-9_.@-]{0,127}$").map_err(|error|format!("POOL_REGEX_FAILED:{error}"))?;if !provider_re.is_match(&provider)||!account_re.is_match(&account){return Err("provider/account contains unsupported characters".to_owned())}Ok((provider,account))}
fn validate_credential(value:&str)->Result<String,String>{let reference=value.trim();let allowed=Regex::new(r"^(?:env|file|keyring|oauth-profile):[A-Za-z0-9_.@/:-]{1,240}$").map_err(|error|format!("POOL_REGEX_FAILED:{error}"))?;let secret=Regex::new(r"(?i)(?:sk-[A-Za-z0-9_-]{16,}|gh[opusr]_[A-Za-z0-9]{20,}|bearer\s+\S+)").map_err(|error|format!("POOL_REGEX_FAILED:{error}"))?;if secret.is_match(reference)||!allowed.is_match(reference){return Err("credential_ref must be a non-secret env/file/keyring/oauth-profile reference".to_owned())}Ok(reference.to_owned())}
fn pool_add(arguments:&[String],connection:&Connection,provider:&str,account:&str,value:&str)->Result<Value,String>{if provider.is_empty()||account.is_empty()||value.is_empty(){return Err("add requires provider account credential_ref".to_owned())}let(provider,account)=validate_provider_account(provider,account)?;let credential=validate_credential(value)?;let quota=option_f64(arguments,"--quota",1.0)?.clamp(0.0,1.0);let reset=option_f64(arguments,"--quota-reset-at",0.0)?;let models=multi_options(arguments,"--model");let now=now_seconds()?;connection.execute("INSERT INTO provider_accounts(provider,account,credential_ref,subscription,priority,quota_remaining,quota_reset_at,model_allowlist_json,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(provider,account) DO UPDATE SET credential_ref=excluded.credential_ref,subscription=excluded.subscription,priority=excluded.priority,quota_remaining=excluded.quota_remaining,quota_reset_at=excluded.quota_reset_at,model_allowlist_json=excluded.model_allowlist_json,disabled=0,updated_at=excluded.updated_at",params![provider,account,credential,i64::from(has_flag(arguments,"--subscription")),option_i64(arguments,"--priority",0)?,quota,reset,canonical_json(&serde_json::to_value(models).map_err(|error|format!("POOL_MODELS_JSON_FAILED:{error}"))?)?,now]).map_err(|error|format!("PROVIDER_POOL_ADD_FAILED:{error}"))?;pool_get(connection,&provider,&account)}
fn pool_get(connection:&Connection,provider:&str,account:&str)->Result<Value,String>{connection.query_row("SELECT provider,account,credential_ref,subscription,priority,quota_remaining,quota_reset_at,rate_limited_until,circuit_open_until,latency_ewma_ms,success_count,failure_count,disabled,model_allowlist_json,updated_at FROM provider_accounts WHERE provider=? AND account=?",params![provider,account],|row|{let success=row.get::<_,i64>(10)?;let failure=row.get::<_,i64>(11)?;let total=success+failure;Ok(json!({"provider":row.get::<_,String>(0)?,"account":row.get::<_,String>(1)?,"credential_ref":row.get::<_,String>(2)?,"subscription":row.get::<_,i64>(3)?!=0,"priority":row.get::<_,i64>(4)?,"quota_remaining":row.get::<_,f64>(5)?,"quota_reset_at":row.get::<_,f64>(6)?,"rate_limited_until":row.get::<_,f64>(7)?,"circuit_open_until":row.get::<_,f64>(8)?,"latency_ewma_ms":row.get::<_,f64>(9)?,"success_count":success,"failure_count":failure,"disabled":row.get::<_,i64>(12)?!=0,"model_allowlist":serde_json::from_str::<Value>(&row.get::<_,String>(13)?).unwrap_or_else(|_|json!([])),"updated_at":row.get::<_,f64>(14)?,"health_ratio":if total==0{1.0}else{success as f64/total as f64}}))}).map_err(|error|format!("PROVIDER_POOL_GET_FAILED:{error}"))}
fn pool_feedback(arguments:&[String],connection:&Connection,provider:&str,account:&str)->Result<Value,String>{let(provider,account)=validate_provider_account(provider,account)?;let success=has_flag(arguments,"--success");let failure=has_flag(arguments,"--failure");if success==failure{return Err("feedback requires exactly one of --success or --failure".to_owned())}let current=pool_get(connection,&provider,&account)?;let now=now_seconds()?;let previous=current["latency_ewma_ms"].as_f64().unwrap_or(0.0);let observed=option_f64(arguments,"--latency-ms",0.0)?.max(0.0);let latency=if previous<=0.0{observed}else{previous*0.8+observed*0.2};let failures=if success{0}else{connection.query_row("SELECT consecutive_failures FROM provider_accounts WHERE provider=? AND account=?",params![provider,account],|row|row.get::<_,i64>(0)).unwrap_or(0)+1};let circuit=if success{0.0}else if failures>=3{now+(30.0*2f64.powi((failures-3).min(5) as i32)).min(900.0)}else{current["circuit_open_until"].as_f64().unwrap_or(0.0)};let retry=option_f64(arguments,"--retry-after",0.0)?.max(0.0);let rate=current["rate_limited_until"].as_f64().unwrap_or(0.0).max(now+retry);let quota=option_value(arguments,"--quota")?.map(|value|value.parse::<f64>().map_err(|_|"POOL_QUOTA_INVALID".to_owned())).transpose()?.unwrap_or_else(||current["quota_remaining"].as_f64().unwrap_or(1.0)).clamp(0.0,1.0);let reset=option_value(arguments,"--quota-reset-at")?.map(|value|value.parse::<f64>().map_err(|_|"POOL_RESET_INVALID".to_owned())).transpose()?.unwrap_or_else(||current["quota_reset_at"].as_f64().unwrap_or(0.0));connection.execute("UPDATE provider_accounts SET quota_remaining=?,quota_reset_at=?,rate_limited_until=?,circuit_open_until=?,latency_ewma_ms=?,success_count=success_count+?,failure_count=failure_count+?,consecutive_failures=?,updated_at=? WHERE provider=? AND account=?",params![quota,reset,rate,circuit,latency,i64::from(success),i64::from(failure),failures,now,provider,account]).map_err(|error|format!("PROVIDER_POOL_FEEDBACK_FAILED:{error}"))?;pool_get(connection,&provider,&account)}
fn pool_list(connection:&Connection)->Result<Vec<Value>,String>{let mut statement=connection.prepare("SELECT provider,account FROM provider_accounts ORDER BY provider,priority DESC,account").map_err(|error|format!("POOL_LIST_PREPARE_FAILED:{error}"))?;let pairs=statement.query_map([],|row|Ok((row.get::<_,String>(0)?,row.get::<_,String>(1)?))).map_err(|error|format!("POOL_LIST_QUERY_FAILED:{error}"))?.collect::<Result<Vec<_>,_>>().map_err(|error|format!("POOL_LIST_ROW_FAILED:{error}"))?;pairs.into_iter().map(|(p,a)|pool_get(connection,&p,&a)).collect()}
fn pool_receipt(connection:&Connection)->Result<Value,String>{let accounts=pool_list(connection)?;let mut body=json!({"schema_version":1,"accounts":accounts});body["receipt_hash"]=Value::String(sha256_hex(canonical_json(&body)?.as_bytes()));Ok(body)}
fn pool_candidates(connection:&Connection,models:&[Value],now:f64,provider_filter:&str)->Result<Vec<Value>,String>{let accounts=pool_list(connection)?;let mut output=Vec::new();for model in models{let provider=model["provider"].as_str().unwrap_or_default().to_lowercase();if !provider_filter.is_empty()&&provider_filter!=provider{continue}for account in &accounts{if account["provider"].as_str()!=Some(provider.as_str())||account["disabled"].as_bool().unwrap_or(false){continue}let allow=account["model_allowlist"].as_array().cloned().unwrap_or_default();let model_name=model["model"].as_str().unwrap_or_default();if !allow.is_empty()&&!allow.iter().any(|value|value.as_str()==Some(model_name)){continue}let quota=if account["quota_reset_at"].as_f64().unwrap_or(0.0)>0.0&&account["quota_reset_at"].as_f64().unwrap_or(0.0)<=now{1.0}else{account["quota_remaining"].as_f64().unwrap_or(1.0)};let subscription=account["subscription"].as_bool().unwrap_or(false);output.push(json!({"provider":provider,"model":model_name,"available":account["circuit_open_until"].as_f64().unwrap_or(0.0)<=now,"quota_remaining":quota,"rate_limited_until":account["rate_limited_until"].as_f64().unwrap_or(0.0),"input_cost_per_million":if subscription{0.0}else{model["input_cost_per_million"].as_f64().unwrap_or(0.0)},"output_cost_per_million":if subscription{0.0}else{model["output_cost_per_million"].as_f64().unwrap_or(0.0)},"latency_ms":if account["latency_ewma_ms"].as_f64().unwrap_or(0.0)>0.0{account["latency_ewma_ms"].as_f64().unwrap_or(0.0)}else{model["latency_ms"].as_f64().unwrap_or(0.0)},"quality":model["quality"].as_f64().unwrap_or(0.5)*(0.75+0.25*account["health_ratio"].as_f64().unwrap_or(1.0)),"max_complexity":model["max_complexity"].as_str().unwrap_or("reasoning"),"context_window":model["context_window"].as_i64().unwrap_or(0),"account":account["account"],"subscription":subscription,"priority":account["priority"]}));}}Ok(output)}

fn delegate_action(arguments:&[String])->Result<Value,String>{let objective=positional_after(arguments,"delegate",0,&["--context-path","--max-tasks"])?;let paths=multi_options(arguments,"--context-path");let max_tasks=option_i64(arguments,"--max-tasks",8)?.max(0) as usize;let sentences=split_sentences(objective);let mut groups=BTreeMap::<String,Vec<String>>::new();for sentence in &sentences{let lower=sentence.to_lowercase();let capability=if ["test","coverage","verify","benchmark"].iter().any(|term|lower.contains(term)){"verification"}else if ["security","secret","permission","auth","sandbox"].iter().any(|term|lower.contains(term)){"security"}else if ["ui","dashboard","extension","frontend","statusline"].iter().any(|term|lower.contains(term)){"interface"}else if ["database","schema","migration","index","memory"].iter().any(|term|lower.contains(term)){"data"}else if ["provider","model","routing","quota","rate limit"].iter().any(|term|lower.contains(term)){"provider"}else if ["ast","symbol","call graph","class hierarchy","refactor"].iter().any(|term|lower.contains(term)){"code-intelligence"}else{"implementation"};groups.entry(capability.to_owned()).or_default().push(sentence.clone());}if groups.len()<=1&&sentences.len()<=3{let mut body=json!({"delegated":false,"reason":"task is small enough for one agent","tasks":[]});body["receipt_hash"]=Value::String(sha256_hex(canonical_json(&body)?.as_bytes()));return Ok(body)}let mut tasks=Vec::<Value>::new();let mut previous=Vec::<String>::new();for(index,(capability,items))in groups.iter().enumerate(){if tasks.len()>=max_tasks{break}let id=format!("T{:02}",index+1);let dependencies=previous.iter().rev().take(2).cloned().collect::<Vec<_>>().into_iter().rev().collect::<Vec<_>>();tasks.push(json!({"id":id,"title":capability.replace('-',' ').split_whitespace().map(capitalize).collect::<Vec<_>>().join(" "),"objective":items.join(" "),"capability":capability,"context_paths":paths,"dependencies":dependencies,"max_output_tokens":1200,"handoff":format!("{id} {capability}: return decisions, changed paths, verification commands, blockers; omit narration.")}));previous.push(id);}let mut body=json!({"delegated":true,"reason":"independent capability groups detected","tasks":tasks});body["receipt_hash"]=Value::String(sha256_hex(canonical_json(&body)?.as_bytes()));Ok(body)}
fn capitalize(value:&str)->String{let mut chars=value.chars();match chars.next(){Some(first)=>first.to_uppercase().collect::<String>()+chars.as_str(),None=>String::new()}}
fn split_sentences(value:&str)->Vec<String>{let re=Regex::new(r"(?:\n+|[.!?]+\s+)").expect("static regex");re.split(value).map(|row|row.trim_matches(|c:char|c==' '||c=='-'||c=='*'||c=='\t').trim()).filter(|row|row.len()>=8).map(str::to_owned).collect()}

fn snapshot_path(state_root:&Path)->PathBuf{state_root.join("watcher/snapshot.json")}
fn repository_snapshot(project:&Path)->Result<BTreeMap<String,String>,String>{let mut output=BTreeMap::new();visit_project(project,project,&mut|relative,path|{let bytes=fs::read(path).map_err(|error|format!("WATCH_FILE_READ_FAILED:{error}"))?;output.insert(relative.to_owned(),sha256_hex(&bytes));Ok(())})?;Ok(output)}
fn watch_action(arguments:&[String],project:&Path,state_root:&Path)->Result<Value,String>{let iterations=option_i64(arguments,"--iterations",1)?.max(0) as usize;let interval=option_f64(arguments,"--interval",1.0)?.max(0.0);let no_index=has_flag(arguments,"--no-index");let mut changes=Vec::<Value>::new();for step in 0..iterations{let current=repository_snapshot(project)?;let old=load_snapshot(state_root)?;let added=current.keys().filter(|key|!old.contains_key(*key)).cloned().collect::<Vec<_>>();let modified=current.iter().filter(|(key,value)|old.get(*key).is_some_and(|old_hash|old_hash!=*value)).map(|(key,_)|key.clone()).collect::<Vec<_>>();let deleted=old.keys().filter(|key|!current.contains_key(*key)).cloned().collect::<Vec<_>>();let changed=added.iter().chain(modified.iter()).chain(deleted.iter()).cloned().collect::<Vec<_>>();save_snapshot(state_root,&current)?;if !no_index&&!changed.is_empty(){let command=vec!["run".to_owned(),"graph-index".to_owned()];let args=vec!["run".to_owned(),"graph-index".to_owned()];let _=super::native_remaining71_graph::execute(&command,&args,project,state_root);}changes.push(json!({"added":added,"modified":modified,"deleted":deleted,"changed":changed,"observed_at":now_seconds()?}));if step+1<iterations&&interval>0.0{std::thread::sleep(Duration::from_secs_f64(interval));}}let current=load_snapshot(state_root)?;Ok(json!({"changes":changes,"status":{"ok":true,"files":current.len(),"snapshot":snapshot_path(state_root).to_string_lossy()}}))}
fn load_snapshot(state_root:&Path)->Result<BTreeMap<String,String>,String>{let path=snapshot_path(state_root);if !path.is_file(){return Ok(BTreeMap::new())}serde_json::from_slice(&fs::read(path).map_err(|error|format!("WATCH_SNAPSHOT_READ_FAILED:{error}"))?).map_err(|error|format!("WATCH_SNAPSHOT_JSON_FAILED:{error}"))}
fn save_snapshot(state_root:&Path,value:&BTreeMap<String,String>)->Result<(),String>{let path=snapshot_path(state_root);if let Some(parent)=path.parent(){fs::create_dir_all(parent).map_err(|error|format!("WATCH_SNAPSHOT_PARENT_FAILED:{error}"))?;}atomic_write_json(&path,&serde_json::to_value(value).map_err(|error|format!("WATCH_SNAPSHOT_VALUE_FAILED:{error}"))?)}
fn visit_project<F>(root:&Path,directory:&Path,callback:&mut F)->Result<(),String>where F:FnMut(&str,&Path)->Result<(),String>{let ignored=[".git",".syntavra","node_modules",".venv","venv","dist","build","target","__pycache__"];
let mut entries=fs::read_dir(directory).map_err(|error|format!("WATCH_DIRECTORY_READ_FAILED:{error}"))?.collect::<Result<Vec<_>,_>>().map_err(|error|format!("WATCH_ENTRY_FAILED:{error}"))?;entries.sort_by_key(|entry|entry.file_name());for entry in entries{let path=entry.path();let kind=entry.file_type().map_err(|error|format!("WATCH_TYPE_FAILED:{error}"))?;if kind.is_dir(){if path.file_name().and_then(|value|value.to_str()).is_some_and(|name|ignored.contains(&name)){continue}visit_project(root,&path,callback)?;}else if kind.is_file(){let relative=path.strip_prefix(root).map_err(|_|"WATCH_RELATIVE_FAILED".to_owned())?.to_string_lossy().replace('\\',"/");callback(&relative,&path)?;}}Ok(())}

fn worker_action(arguments:&[String],project:&Path,state_root:&Path)->Result<Value,String>{let action=positional_after(arguments,"worker",0,&["--iterations","--interval"])?;let status_path=state_root.join("worker/status.json");match action{"status"=>{if !status_path.is_file(){return Ok(json!({"ok":true,"running":false,"iterations":0}))}load_json(status_path.to_str().unwrap_or_default())},"run"=>{let iterations=option_i64(arguments,"--iterations",1)?.max(0);let interval=option_f64(arguments,"--interval",2.0)?.max(0.0);let started=now_seconds()?;let mut processed=0;for index in 0..iterations{let command=vec!["run".to_owned(),"graph-index".to_owned()];let args=vec!["run".to_owned(),"graph-index".to_owned()];let _=super::native_remaining71_graph::execute(&command,&args,project,state_root);processed+=1;if index+1<iterations&&interval>0.0{std::thread::sleep(Duration::from_secs_f64(interval));}}let value=json!({"ok":true,"running":false,"iterations":processed,"started_at":started,"finished_at":now_seconds()?});if let Some(parent)=status_path.parent(){fs::create_dir_all(parent).map_err(|error|format!("WORKER_STATUS_PARENT_FAILED:{error}"))?;}atomic_write_json(&status_path,&value)?;Ok(value)},"start"=>{let exe=std::env::current_exe().map_err(|error|format!("WORKER_EXE_FAILED:{error}"))?;let mut command=Command::new(exe);command.args(["--project",project.to_str().unwrap_or_default(),"--state-root",state_root.to_str().unwrap_or_default(),"run","worker","run","--iterations",&option_i64(arguments,"--iterations",1)?.to_string(),"--interval",&option_f64(arguments,"--interval",2.0)?.to_string()]).env("SYNTAVRA_BULK_PARITY_PROBE","1").stdin(Stdio::null()).stdout(Stdio::null()).stderr(Stdio::null());let child=command.spawn().map_err(|error|format!("WORKER_SPAWN_FAILED:{error}"))?;Ok(json!({"ok":true,"running":true,"pid":child.id()}))},_=>Err(format!("WORKER_ACTION_INVALID:{action}"))}}

fn dashboard_action(arguments:&[String],project:&Path,state_root:&Path)->Result<Value,String>{if !has_flag(arguments,"--snapshot"){return Err("native dashboard server requires --snapshot in bounded CLI mode".to_owned())}let graph=graph_stats_value(project,state_root)?;let cache=cache_health(state_root)?;let worker=if state_root.join("worker/status.json").is_file(){load_json(state_root.join("worker/status.json").to_str().unwrap_or_default()).unwrap_or_else(|_|json!({}))}else{json!({"ok":true,"running":false})};Ok(json!({"product":"Syntavra","version":"0.0.1","channel":"pre-release","project":project.to_string_lossy(),"graph":graph,"cache":cache,"worker":worker,"statusline":"[SYN:NATIVE]","generated_at":now_seconds()?}))}

fn code_intel(arguments:&[String],project:&Path,state_root:&Path)->Result<Value,String>{let values=positionals_after(arguments,"code-intel",&["--path","--target-name"])?;let action=values.first().copied().unwrap_or("report");let query=values.get(1).copied().unwrap_or_default();let index_command=vec!["run".to_owned(),"graph-index".to_owned()];let index_args=vec!["run".to_owned(),"graph-index".to_owned()];let report=super::native_remaining71_graph::execute(&index_command,&index_args,project,state_root)?.unwrap_or_else(||json!({}));let db=Connection::open(state_root.join("unified/semantic-graph.sqlite3")).map_err(|error|format!("CODE_INTEL_DB_OPEN_FAILED:{error}"))?;match action{"report"=>Ok(report),"parser-manifest"=>Ok(json!({"declared_language_count":report["language_platform"]["registered_languages"],"languages":report["languages"],"claim_boundary":"exact semantic claims require evidence-graded parser or imported semantic evidence"})),"call"=>hierarchy(&db,query,"calls"),"class"=>class_hierarchy(&db,query),"implementations"=>implementations(&db,query),"blast-radius"=>blast_radius(&db,query),"dead"=>dead_code(&db),"untested"=>untested(&db),"provenance"=>provenance(&db,query),"risk"=>risk_for_paths(&db,&multi_options(arguments,"--path")),"pagerank"=>pagerank(&db),"hotspots"=>hotspots(&db),"cycles"=>cycles(&db),"coupling"=>coupling(&db),"boundaries"=>boundaries(&db),"signal"=>signal_chain(&db,query),"duplicates"=>duplicates(&db),"delete"=>delete_safe(&db,query),"refactor"=>refactor_plan(&db,query,&option_value(arguments,"--target-name")?.unwrap_or_default()),"anti-patterns"=>anti_patterns(&db),"cross-repo"=>Ok(json!({"repositories":multi_options(arguments,"--path"),"contracts":[],"claim_boundary":"cross-repository contracts require explicit indexed repositories"})),_=>Err(format!("CODE_INTEL_ACTION_INVALID:{action}"))}}
fn graph_stats_value(project:&Path,state_root:&Path)->Result<Value,String>{let command=vec!["run".to_owned(),"graph-index".to_owned()];let args=vec!["run".to_owned(),"graph-index".to_owned()];Ok(super::native_remaining71_graph::execute(&command,&args,project,state_root)?.unwrap_or_else(||json!({})))}
fn find_nodes(db:&Connection,query:&str)->Result<Vec<Value>,String>{let pattern=format!("%{}%",query.to_lowercase());let mut statement=db.prepare("SELECT node_id,path,kind,name,qualified_name,start_line,end_line,language,evidence_ref,metadata_json FROM nodes WHERE lower(name)=lower(?) OR lower(qualified_name) LIKE ? ORDER BY path,start_line LIMIT 50").map_err(|error|format!("CODE_NODE_PREPARE_FAILED:{error}"))?;let rows=statement.query_map(params![query,pattern],|row|Ok(json!({"node_id":row.get::<_,String>(0)?,"path":row.get::<_,String>(1)?,"kind":row.get::<_,String>(2)?,"name":row.get::<_,String>(3)?,"qualified_name":row.get::<_,String>(4)?,"start_line":row.get::<_,i64>(5)?,"end_line":row.get::<_,i64>(6)?,"language":row.get::<_,String>(7)?,"evidence_ref":row.get::<_,String>(8)?,"metadata":serde_json::from_str::<Value>(&row.get::<_,String>(9)?).unwrap_or_else(|_|json!({}))}))).map_err(|error|format!("CODE_NODE_QUERY_FAILED:{error}"))?;rows.collect::<Result<Vec<_>,_>>().map_err(|error|format!("CODE_NODE_ROW_FAILED:{error}"))}
fn hierarchy(db:&Connection,query:&str,edge_type:&str)->Result<Value,String>{let matches=find_nodes(db,query)?;let mut results=Vec::new();for node in &matches{let id=node["node_id"].as_str().unwrap_or_default();let mut statement=db.prepare("SELECT source,target,edge_type,confidence FROM edges WHERE (source=? OR target=?) AND edge_type LIKE ? ORDER BY source,target").map_err(|error|format!("CODE_EDGE_PREPARE_FAILED:{error}"))?;let edges=statement.query_map(params![id,id,format!("%{edge_type}%")],|row|Ok(json!({"source":row.get::<_,String>(0)?,"target":row.get::<_,String>(1)?,"edge_type":row.get::<_,String>(2)?,"confidence":row.get::<_,f64>(3)?}))).map_err(|error|format!("CODE_EDGE_QUERY_FAILED:{error}"))?.collect::<Result<Vec<_>,_>>().map_err(|error|format!("CODE_EDGE_ROW_FAILED:{error}"))?;results.push(json!({"symbol":node,"edges":edges}));}Ok(json!({"query":query,"matches":results}))}
fn class_hierarchy(db:&Connection,query:&str)->Result<Value,String>{let matches=find_nodes(db,query)?;let mut rows=Vec::new();for node in matches{if node["kind"].as_str().is_some_and(|kind|kind.contains("class")||kind.contains("type")||kind=="symbol-candidate"){rows.push(node)}}Ok(json!({"query":query,"matches":rows}))}
fn implementations(db:&Connection,query:&str)->Result<Value,String>{let matches=find_nodes(db,query)?;let mut impls=Vec::new();for node in &matches{let id=node["node_id"].as_str().unwrap_or_default();let mut statement=db.prepare("SELECT source FROM edges WHERE target=? AND edge_type IN ('implements','inherits','overrides')").map_err(|error|format!("CODE_IMPL_PREPARE_FAILED:{error}"))?;let ids=statement.query_map(params![id],|row|row.get::<_,String>(0)).map_err(|error|format!("CODE_IMPL_QUERY_FAILED:{error}"))?.collect::<Result<Vec<_>,_>>().map_err(|error|format!("CODE_IMPL_ROW_FAILED:{error}"))?;for source in ids{if let Some(value)=node_by_id(db,&source)?{impls.push(value)}}}Ok(json!({"query":query,"matches":matches,"implementations":impls,"implementation_count":impls.len()}))}
fn node_by_id(db:&Connection,id:&str)->Result<Option<Value>,String>{db.query_row("SELECT node_id,path,kind,name,qualified_name,start_line,end_line,language,evidence_ref,metadata_json FROM nodes WHERE node_id=?",params![id],|row|Ok(json!({"node_id":row.get::<_,String>(0)?,"path":row.get::<_,String>(1)?,"kind":row.get::<_,String>(2)?,"name":row.get::<_,String>(3)?,"qualified_name":row.get::<_,String>(4)?,"start_line":row.get::<_,i64>(5)?,"end_line":row.get::<_,i64>(6)?,"language":row.get::<_,String>(7)?,"evidence_ref":row.get::<_,String>(8)?,"metadata":serde_json::from_str::<Value>(&row.get::<_,String>(9)?).unwrap_or_else(|_|json!({}))}))).optional().map_err(|error|format!("CODE_NODE_ID_QUERY_FAILED:{error}"))}
fn blast_radius(db:&Connection,query:&str)->Result<Value,String>{let matches=find_nodes(db,query)?;let mut impacted=BTreeSet::new();for node in &matches{let id=node["node_id"].as_str().unwrap_or_default();let mut queue=VecDeque::from([id.to_owned()]);let mut seen=BTreeSet::from([id.to_owned()]);while let Some(current)=queue.pop_front(){let mut statement=db.prepare("SELECT source FROM edges WHERE target=?").map_err(|error|format!("BLAST_PREPARE_FAILED:{error}"))?;let ids=statement.query_map(params![current],|row|row.get::<_,String>(0)).map_err(|error|format!("BLAST_QUERY_FAILED:{error}"))?.collect::<Result<Vec<_>,_>>().map_err(|error|format!("BLAST_ROW_FAILED:{error}"))?;for source in ids{if seen.insert(source.clone()){if let Some(value)=node_by_id(db,&source)?{if let Some(path)=value["path"].as_str(){impacted.insert(path.to_owned());}}queue.push_back(source);}}}}Ok(json!({"query":query,"matches":matches,"impacted_paths":impacted}))}
fn dead_code(db:&Connection)->Result<Value,String>{let mut statement=db.prepare("SELECT node_id FROM nodes WHERE kind!='module' AND kind!='external' AND node_id NOT IN (SELECT target FROM edges) AND node_id NOT IN (SELECT source FROM edges WHERE edge_type LIKE 'test%') ORDER BY path,start_line").map_err(|error|format!("DEAD_PREPARE_FAILED:{error}"))?;let ids=statement.query_map([],|row|row.get::<_,String>(0)).map_err(|error|format!("DEAD_QUERY_FAILED:{error}"))?.collect::<Result<Vec<_>,_>>().map_err(|error|format!("DEAD_ROW_FAILED:{error}"))?;Ok(Value::Array(ids.into_iter().filter_map(|id|node_by_id(db,&id).ok().flatten().map(|symbol|json!({"symbol":symbol,"reason":"no incoming graph references"}))).collect()))}
fn untested(db:&Connection)->Result<Value,String>{let dead=dead_code(db)?.as_array().cloned().unwrap_or_default();Ok(Value::Array(dead.into_iter().filter(|row|!row["symbol"]["path"].as_str().unwrap_or_default().to_lowercase().contains("test")).collect()))}
fn provenance(db:&Connection,query:&str)->Result<Value,String>{let nodes=find_nodes(db,query)?;Ok(Value::Array(nodes.into_iter().map(|node|json!({"symbol":node,"evidence_ref":node["evidence_ref"],"metadata":node["metadata"]})).collect()))}
fn risk_for_paths(db:&Connection,paths:&[String])->Result<Value,String>{let mut rows=Vec::new();for path in paths{let symbols=db.query_row("SELECT COUNT(*) FROM nodes WHERE path=?",params![path],|row|row.get::<_,i64>(0)).unwrap_or(0);let edges=db.query_row("SELECT COUNT(*) FROM edges WHERE source IN (SELECT node_id FROM nodes WHERE path=?) OR target IN (SELECT node_id FROM nodes WHERE path=?)",params![path,path],|row|row.get::<_,i64>(0)).unwrap_or(0);rows.push(json!({"path":path,"symbols":symbols,"edges":edges,"risk_score":symbols+edges*2}));}Ok(json!({"paths":rows,"risk":if rows.iter().map(|row|row["risk_score"].as_i64().unwrap_or(0)).sum::<i64>()>100{"high"}else{"low"}}))}
fn pagerank(db:&Connection)->Result<Value,String>{let mut statement=db.prepare("SELECT n.node_id,n.name,n.path,COUNT(e.source)+COUNT(e2.target) degree FROM nodes n LEFT JOIN edges e ON e.target=n.node_id LEFT JOIN edges e2 ON e2.source=n.node_id WHERE n.kind!='external' GROUP BY n.node_id ORDER BY degree DESC,n.path LIMIT 200").map_err(|error|format!("PAGERANK_PREPARE_FAILED:{error}"))?;let rows=statement.query_map([],|row|Ok(json!({"node_id":row.get::<_,String>(0)?,"name":row.get::<_,String>(1)?,"path":row.get::<_,String>(2)?,"score":row.get::<_,i64>(3)?}))).map_err(|error|format!("PAGERANK_QUERY_FAILED:{error}"))?;Ok(Value::Array(rows.collect::<Result<Vec<_>,_>>().map_err(|error|format!("PAGERANK_ROW_FAILED:{error}"))?))}
fn hotspots(db:&Connection)->Result<Value,String>{pagerank(db)}
fn cycles(db:&Connection)->Result<Value,String>{let mut statement=db.prepare("SELECT a.source,a.target FROM edges a JOIN edges b ON a.source=b.target AND a.target=b.source WHERE a.source<a.target ORDER BY a.source").map_err(|error|format!("CYCLE_PREPARE_FAILED:{error}"))?;let rows=statement.query_map([],|row|Ok(json!([row.get::<_,String>(0)?,row.get::<_,String>(1)?]))).map_err(|error|format!("CYCLE_QUERY_FAILED:{error}"))?;Ok(Value::Array(rows.collect::<Result<Vec<_>,_>>().map_err(|error|format!("CYCLE_ROW_FAILED:{error}"))?))}
fn coupling(db:&Connection)->Result<Value,String>{let mut statement=db.prepare("SELECT a.path,b.path,COUNT(*) c FROM edges e JOIN nodes a ON a.node_id=e.source JOIN nodes b ON b.node_id=e.target WHERE a.path!=b.path GROUP BY a.path,b.path ORDER BY c DESC,a.path,b.path LIMIT 200").map_err(|error|format!("COUPLING_PREPARE_FAILED:{error}"))?;let rows=statement.query_map([],|row|Ok(json!({"source":row.get::<_,String>(0)?,"target":row.get::<_,String>(1)?,"weight":row.get::<_,i64>(2)?}))).map_err(|error|format!("COUPLING_QUERY_FAILED:{error}"))?;Ok(Value::Array(rows.collect::<Result<Vec<_>,_>>().map_err(|error|format!("COUPLING_ROW_FAILED:{error}"))?))}
fn boundaries(db:&Connection)->Result<Value,String>{let mut statement=db.prepare("SELECT CASE WHEN instr(path,'/')=0 THEN '.' ELSE substr(path,1,instr(path,'/')-1) END module,COUNT(DISTINCT path),COUNT(*) FROM nodes WHERE kind!='external' GROUP BY module ORDER BY module").map_err(|error|format!("BOUNDARY_PREPARE_FAILED:{error}"))?;let rows=statement.query_map([],|row|Ok(json!({"module":row.get::<_,String>(0)?,"files":row.get::<_,i64>(1)?,"symbols":row.get::<_,i64>(2)?}))).map_err(|error|format!("BOUNDARY_QUERY_FAILED:{error}"))?.collect::<Result<Vec<_>,_>>().map_err(|error|format!("BOUNDARY_ROW_FAILED:{error}"))?;Ok(json!({"modules":rows}))}
fn signal_chain(db:&Connection,query:&str)->Result<Value,String>{let blast=blast_radius(db,query)?;Ok(json!({"query":query,"signal_chain":blast["impacted_paths"],"matches":blast["matches"]}))}
fn duplicates(db:&Connection)->Result<Value,String>{let mut statement=db.prepare("SELECT name,COUNT(*) c FROM nodes WHERE kind!='external' GROUP BY lower(name) HAVING c>1 ORDER BY c DESC,name LIMIT 200").map_err(|error|format!("DUP_PREPARE_FAILED:{error}"))?;let rows=statement.query_map([],|row|Ok(json!({"name":row.get::<_,String>(0)?,"count":row.get::<_,i64>(1)?}))).map_err(|error|format!("DUP_QUERY_FAILED:{error}"))?;Ok(Value::Array(rows.collect::<Result<Vec<_>,_>>().map_err(|error|format!("DUP_ROW_FAILED:{error}"))?))}
fn delete_safe(db:&Connection,query:&str)->Result<Value,String>{let matches=find_nodes(db,query)?;let mut incoming=0i64;for node in &matches{incoming+=db.query_row("SELECT COUNT(*) FROM edges WHERE target=?",params![node["node_id"].as_str().unwrap_or_default()],|row|row.get::<_,i64>(0)).unwrap_or(0);}Ok(json!({"query":query,"matches":matches,"safe":incoming==0,"incoming_references":incoming}))}
fn refactor_plan(db:&Connection,query:&str,target:&str)->Result<Value,String>{let matches=find_nodes(db,query)?;Ok(json!({"query":query,"target_name":target,"matches":matches,"steps":["rename declaration","update graph-resolved references","run affected tests","verify no stale references"],"safe_to_apply_automatically":false}))}
fn anti_patterns(db:&Connection)->Result<Value,String>{let dead=dead_code(db)?.as_array().cloned().unwrap_or_default();Ok(Value::Array(dead.into_iter().take(100).map(|row|json!({"kind":"dead-symbol","symbol":row["symbol"]})).collect()))}

fn atomic_write_json(path:&Path,value:&Value)->Result<(),String>{if let Some(parent)=path.parent(){fs::create_dir_all(parent).map_err(|error|format!("ATOMIC_PARENT_FAILED:{error}"))?;}let temp=path.with_extension(format!("{}.tmp",std::process::id()));fs::write(&temp,serde_json::to_vec_pretty(&sort_json(value)).map_err(|error|format!("ATOMIC_JSON_FAILED:{error}"))?).map_err(|error|format!("ATOMIC_WRITE_FAILED:{error}"))?;#[cfg(windows)]if path.exists(){fs::remove_file(path).map_err(|error|format!("ATOMIC_REMOVE_FAILED:{error}"))?;}fs::rename(temp,path).map_err(|error|format!("ATOMIC_RENAME_FAILED:{error}"))}
fn load_json(value:&str)->Result<Value,String>{let raw=if Path::new(value).is_file(){fs::read_to_string(value).map_err(|error|format!("JSON_READ_FAILED:{error}"))?}else{value.to_owned()};serde_json::from_str(&raw).map_err(|error|format!("JSON_INVALID:{error}"))}
fn canonical_json(value:&Value)->Result<String,String>{serde_json::to_string(&sort_json(value)).map_err(|error|format!("JSON_SERIALIZE_FAILED:{error}"))}
fn sort_json(value:&Value)->Value{match value{Value::Object(map)=>{let mut keys=map.keys().collect::<Vec<_>>();keys.sort_unstable();let mut output=Map::new();for key in keys{output.insert(key.clone(),sort_json(&map[key]));}Value::Object(output)},Value::Array(rows)=>Value::Array(rows.iter().map(sort_json).collect()),_=>value.clone()}}
fn command_exists(name:&str)->bool{std::env::var_os("PATH").is_some_and(|path|std::env::split_paths(&path).any(|dir|dir.join(name).is_file()||cfg!(windows)&&[".exe",".cmd",".bat"].iter().any(|suffix|dir.join(format!("{name}{suffix}")).is_file())))}
fn now_seconds()->Result<f64,String>{SystemTime::now().duration_since(UNIX_EPOCH).map(|value|value.as_secs_f64()).map_err(|error|format!("CLOCK_FAILED:{error}"))}
fn has_flag(arguments:&[String],flag:&str)->bool{arguments.iter().any(|value|value==flag)}
fn option_value(arguments:&[String],flag:&str)->Result<Option<String>,String>{let mut output=None;let mut index=0usize;while index<arguments.len(){let current=&arguments[index];let found=if current==flag{index+=1;Some(arguments.get(index).ok_or_else(||format!("{flag}_VALUE_MISSING"))?.clone())}else{current.strip_prefix(flag).and_then(|tail|tail.strip_prefix('=')).map(str::to_owned)};if let Some(found)=found{output=Some(found);}index+=1;}Ok(output)}
fn required_option(arguments:&[String],flag:&str)->Result<String,String>{option_value(arguments,flag)?.ok_or_else(||format!("{flag}_REQUIRED"))}
fn option_i64(arguments:&[String],flag:&str,default:i64)->Result<i64,String>{option_value(arguments,flag)?.map(|value|value.parse::<i64>().map_err(|_|format!("{flag}_INVALID"))).transpose().map(|value|value.unwrap_or(default))}
fn option_f64(arguments:&[String],flag:&str,default:f64)->Result<f64,String>{option_value(arguments,flag)?.map(|value|value.parse::<f64>().map_err(|_|format!("{flag}_INVALID"))).transpose().map(|value|value.unwrap_or(default))}
fn multi_options(arguments:&[String],flag:&str)->Vec<String>{let mut output=Vec::new();let mut index=0usize;while index<arguments.len(){if arguments[index]==flag{if let Some(value)=arguments.get(index+1){output.push(value.clone());}index+=2;continue}if let Some(value)=arguments[index].strip_prefix(&format!("{flag}=")){output.push(value.to_owned());}index+=1;}output}
fn positionals_after<'a>(arguments:&'a[String],action:&str,value_flags:&[&str])->Result<Vec<&'a str>,String>{let mut index=arguments.windows(2).position(|row|row[0]=="run"&&row[1]==action).map(|index|index+2).ok_or_else(||format!("ACTION_NOT_FOUND:{action}"))?;let mut values=Vec::new();while index<arguments.len(){if value_flags.contains(&arguments[index].as_str()){index+=2;continue}if arguments[index].starts_with("--"){index+=1;continue}values.push(arguments[index].as_str());index+=1;}Ok(values)}
fn positional_after<'a>(arguments:&'a[String],action:&str,position:usize,value_flags:&[&str])->Result<&'a str,String>{positionals_after(arguments,action,value_flags)?.get(position).copied().ok_or_else(||format!("POSITIONAL_MISSING:{action}:{position}"))}
